### ISSUE TITLE
003.网站部署

### ISSUE THREAD

**Issue by datscicn** [datscicn/datscicn.github.io#3]
部署

**Comment by datscicn** [comment]
1. 安装 hexo-deployer-git
```npm install hexo-deployer-git --save```

2. 修改_config.yml文件
部署到Github前需要配置_config.yml文件，首先找到下面的内容
```# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:
```
然后将它们修改为
```
# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:datscicn/datscicn.github.io.git
  branch: master
```
3 .部署到 GitHub
hexo clean  # 删除原来的静态页面
hexo g  # generate 生成新的静态页面
hexo d  # deploy 将页面部署到 GitHub 上
访问 https://datscicn.github.io 就可以看到你的博客网站了！
